org: irisfu
app: drop-backend
service: drop-backend
frameworkVersion: '3'

custom:
  clientsTableName: 'clients-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"
            
  environment:
    DYNAMODB_NAMESPACE: ${opt:stage, "dev"}

functions:
  createClient:
    handler: src/handler/client.createClient
    events:
      - httpApi:
          method: POST
          path: /client

  createDocument:
    handler: src/handler/document.createDocument
    events:
      - httpApi:
          method: POST
          path: /document

  getAllDocuments:
    handler: src/handler/document.getAllDocuments
    events:
      - httpApi:
          method: GET
          path: /documents/{clientId}

  createExplanation:
    handler: src/handler/explanation.createExplanation
    events:
      - httpApi:
          method: POST
          path: /explanation

  getAllExplanations:
    handler: src/handler/explanation.getAllExplanations
    events:
      - httpApi:
          method: GET
          path: /explanations/{documentId}

resources:
  Resources:
    ClientsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: 'clientsTable'
        AttributeDefinitions:
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: clientId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    
    DocumentTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: documentId
            AttributeType: S
          -
            AttributeName: clientId
            AttributeType: S  
        KeySchema:
          -
            AttributeName: documentId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'documentsTable'
        GlobalSecondaryIndexes:
          -
            IndexName: client
            KeySchema:
              -
                AttributeName: clientId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

    ExplanationTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: documentId
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'explanationsTable'
        GlobalSecondaryIndexes:
          -
            IndexName: document
            KeySchema:
              -
                AttributeName: documentId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1   
